language: php

php: [7.1]

before_script:
  - composer selfupdate
  - composer install --dev

script:
  - vendor/bin/kahlan --reporter=verbose --clover=coverage.xml

after_script:
  - php vendor/bin/coveralls
